name: test_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  # Networking
  http: ^1.1.0
  dio: ^5.0.0

  # Routing
  go_router: ^14.0.0

  # State management
  flutter_bloc: ^8.1.0

  # Secure storage for JWT tokens
  flutter_secure_storage: ^9.0.0

  # WebSocket client
  socket_io_client: ^2.0.2


  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.0

  cupertino_icons: ^1.0.2

  image_picker: ^1.0.4
  path_provider: ^2.1.2
  image_cropper: ^11.0.0
  # OpenStreetMap via flutter_map (no API key required)
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^9.0.2

flutter:
  uses-material-design: true
